### ISSUE TITLE
Remove annotations and reference JB package instead

### ISSUE THREAD

**Issue by Zvirja** [Sitecore/Sitecore.Diagnostics.Base#2]
Remove embedded annotations and reference the [JB nuget package](https://www.nuget.org/packages/JetBrains.Annotations) instead.

This is a compile time dependency and you will not see assembly reference in produced artifact.

The reason is that current assembly doesn't contain the complete list of annotations - some are missed.

Alternatively, update embedded annotations.

**Comment by AlenPelin** [comment]
Makes sense, pull request is appreciated.

**Comment by Zvirja** [comment]
Added Pr #3.

This will be a breaking change for the consumers, because they will need to change their namespace imports (which could be a bit huge change). Therefore, it could be released as a major update only.

If you decide to do a major update, please rename the `Assembly` type to something like `AssemblyInfo`. It isn't a good practice to create a name that has collisions with built-in types.

**Comment by AlenPelin** [comment]
AssemblyInfo.cs is reserved name for Properties/AssemblyInfo.cs which may lead to confuses.

**Comment by Zvirja** [comment]
Indeed, missed that. In this case we need some other name. `Assembly` is confusing as well.

**Comment by AlenPelin** [comment]
I don't see any problem with `Assembly`. In most cases this type is used in Diagnostics Toolset tests where you compare several instances of `Assembly` type. In those rare situations when you need to use both `Reflection.Assembly` and `Diagnostics.Assembly` you can use aliases:
```
using ReflectionAssembly = Reflection.Assembly;
using Diagnostics.Assembly = Diagnostics.Assembly;
```

**Comment by Zvirja** [comment]
OK. I don't work to often with projects, which reference this library, so it's up to you. However, this situation is very annoying because of confusions caused by name collision. For instance, if argument takes assembly parameter, you should manually resolve reference to check which exact type of `Assembly` is used here.

**Comment by AlenPelin** [comment]
The decision to choose `Assembly` over `AssemblyInfo` was hard, believe me, but I made it once and it is better to keep it as is until we have really good reason to change.
